'use strict';

const assert = require('assert');
const assetsTransformer = require('./assets');

describe('Karma', () => {
  describe('Assets transformer', () => {
    it('should fill the manifest', () => {
      expect(
        assetsTransformer(
          {
            name: '.travis.yml',
            data: `# This file is automatically generated by a \`metapak\`
# module. Do not change it elsewhere, changes would
# be overridden.

language: node_js
node_js:
  - 8
  - 8.12.0
  - 9
  - 10
`,
          },
          {},
        ),
      ).toMatchSnapshot();
    });

    it('should let pass other files', () => {
      assert.deepEqual(
        assetsTransformer(
          {
            name: 'YOLO',
            data: 'Carpe diem\n',
          },
          {},
        ),
        {
          name: 'YOLO',
          data: 'Carpe diem\n',
        },
      );
    });
  });
});
